apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: loginkr/u-hub_client:latest
        imagePullPolicy: Always
        ports:
        - name: port
          containerPort: 3000
        envFrom:
        - configMapRef:
            name: amqp
        - configMapRef:
            name: mongo
