apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: client
          servicePort: 80
