apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto
spec:
  clusterIP: None
  selector:
    app: mosquitto
  ports:
  - name: mosquitto
    port: 1883
    protocol: TCP
    targetPort: 1883