sudo: required
services:
  - docker
# branches:
#   only:
#     - master
before_script:
  - export REVISION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo ${TRAVIS_COMMIT::8} ; fi`
  - export APOLLO_IMAGE_TAG=$DOCKER_REPO_APOLLO:$REVISION
  - export APPLE_HOMEKIT_IMAGE_TAG=$DOCKER_REPO_APPLE_HOMEKIT:$REVISION
  - export CLIENT_IMAGE_TAG=$DOCKER_REPO_CLIENT:$REVISION
  - export SCHEDULED_ACTION_IMAGE_TAG=$DOCKER_REPO_SCHEDULED_ACTION:$REVISION
  - export GOOGLE_HOME_IMAGE_TAG=$DOCKER_REPO_GOOGLE_HOME:$REVISION
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - docker build -t $APOLLO_IMAGE_TAG ./apollo
  - docker run $APOLLO_IMAGE_TAG run lint
  - docker run $APOLLO_IMAGE_TAG run test
  - docker push $APOLLO_IMAGE_TAG

  - docker build -t $APPLE_HOMEKIT_IMAGE_TAG ./apple-homekit
  - docker run $APPLE_HOMEKIT_IMAGE_TAG run lint
  - docker run $APPLE_HOMEKIT_IMAGE_TAG run test
  - docker push $APPLE_HOMEKIT_IMAGE_TAG

  - docker build -t $CLIENT_IMAGE_TAG ./client
  - docker run $CLIENT_IMAGE_TAG run lint
  - docker push $CLIENT_IMAGE_TAG

  - docker build -t $SCHEDULED_ACTION_IMAGE_TAG ./scheduled-action
  - docker run $SCHEDULED_ACTION_IMAGE_TAG run lint
  - docker run $SCHEDULED_ACTION_IMAGE_TAG run test
  - docker push $SCHEDULED_ACTION_IMAGE_TAG

  - docker build -t $GOOGLE_HOME_IMAGE_TAG ./google-home
  - docker run $GOOGLE_HOME_IMAGE_TAG run lint
  - docker run $GOOGLE_HOME_IMAGE_TAG run test
  - docker push $GOOGLE_HOME_IMAGE_TAG
