sudo: required
services:
  - docker
language: node_js
node_js:
  - 12
jobs:
  include:
  - stage: build
    script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - export REVISION=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

      - docker build -t $DOCKER_REPO_APOLLO:$REVISION ./services/apollo
      - docker run $DOCKER_REPO_APOLLO:$REVISION run lint
      - docker run $DOCKER_REPO_APOLLO:$REVISION run test
      - docker push $DOCKER_REPO_APOLLO:$REVISION

      - docker build -t $DOCKER_REPO_APPLE_HOMEKIT:$REVISION ./services/apple-homekit
      - docker run $DOCKER_REPO_APPLE_HOMEKIT:$REVISION run lint
      - docker run $DOCKER_REPO_APPLE_HOMEKIT:$REVISION run test
      - docker push $DOCKER_REPO_APPLE_HOMEKIT:$REVISION

      - docker build -t $DOCKER_REPO_CLIENT:$REVISION ./services/client
      - docker run $DOCKER_REPO_CLIENT:$REVISION run lint
      - docker push $DOCKER_REPO_CLIENT:$REVISION

      - docker build -t $DOCKER_REPO_SCHEDULED_ACTION:$REVISION ./cronjobs/scheduled-action
      - docker run $DOCKER_REPO_SCHEDULED_ACTION:$REVISION run lint
      - docker run $DOCKER_REPO_SCHEDULED_ACTION:$REVISION run test
      - docker push $DOCKER_REPO_SCHEDULED_ACTION:$REVISION

      - docker build -t $DOCKER_REPO_GOOGLE_HOME:$REVISION ./services/google-home
      - docker run $DOCKER_REPO_GOOGLE_HOME:$REVISION run lint
      - docker run $DOCKER_REPO_GOOGLE_HOME:$REVISION run test
      - docker push $DOCKER_REPO_GOOGLE_HOME:$REVISION

      - docker build -t $DOCKER_REPO_MQTT_LISTENER:$REVISION ./services/mqtt-listener
      - docker run $DOCKER_REPO_MQTT_LISTENER:$REVISION run lint
      - docker run $DOCKER_REPO_MQTT_LISTENER:$REVISION run test
      - docker push $DOCKER_REPO_MQTT_LISTENER:$REVISION

      - docker build -t $DOCKER_REPO_AUTOMATIC_ACTION:$REVISION ./services/automatic-action
      - docker run $DOCKER_REPO_AUTOMATIC_ACTION:$REVISION run lint
      - docker run $DOCKER_REPO_AUTOMATIC_ACTION:$REVISION run test
      - docker push $DOCKER_REPO_AUTOMATIC_ACTION:$REVISION
  - stage: build_version
    if: tag IS present
    script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - docker build -t $DOCKER_REPO_APOLLO:$TRAVIS_TAG ./apollo
      - docker run $DOCKER_REPO_APOLLO:$TRAVIS_TAG run lint
      - docker run $DOCKER_REPO_APOLLO:$TRAVIS_TAG run test
      - docker push $DOCKER_REPO_APOLLO:$TRAVIS_TAG

      - docker build -t $DOCKER_REPO_APPLE_HOMEKIT:$TRAVIS_TAG ./services/apple-homekit
      - docker run $DOCKER_REPO_APPLE_HOMEKIT:$TRAVIS_TAG run lint
      - docker run $DOCKER_REPO_APPLE_HOMEKIT:$TRAVIS_TAG run test
      - docker push $DOCKER_REPO_APPLE_HOMEKIT:$TRAVIS_TAG

      - docker build -t $DOCKER_REPO_CLIENT:$REVISION ./services/client
      - docker run $DOCKER_REPO_CLIENT:$REVISION run lint
      - docker push $DOCKER_REPO_CLIENT:$REVISION

      - docker build -t $DOCKER_REPO_SCHEDULED_ACTION:$TRAVIS_TAG ./cronjobs/scheduled-action
      - docker run $DOCKER_REPO_SCHEDULED_ACTION:$TRAVIS_TAG run lint
      - docker run $DOCKER_REPO_SCHEDULED_ACTION:$TRAVIS_TAG run test
      - docker push $DOCKER_REPO_SCHEDULED_ACTION:$TRAVIS_TAG

      - docker build -t $DOCKER_REPO_GOOGLE_HOME:$TRAVIS_TAG ./services/google-home
      - docker run $DOCKER_REPO_GOOGLE_HOME:$TRAVIS_TAG run lint
      - docker run $DOCKER_REPO_GOOGLE_HOME:$TRAVIS_TAG run test
      - docker push $DOCKER_REPO_GOOGLE_HOME:$TRAVIS_TAG

      - docker build -t $DOCKER_REPO_MQTT_LISTENER:$TRAVIS_TAG ./services/mqtt-listener
      - docker run $DOCKER_REPO_MQTT_LISTENER:$TRAVIS_TAG run lint
      - docker run $DOCKER_REPO_MQTT_LISTENER:$TRAVIS_TAG run test
      - docker push $DOCKER_REPO_MQTT_LISTENER:$TRAVIS_TAG

      - docker build -t $DOCKER_REPO_AUTOMATIC_ACTION:$TRAVIS_TAG ./services/automatic-action
      - docker run $DOCKER_REPO_AUTOMATIC_ACTION:$TRAVIS_TAG run lint
      - docker run $DOCKER_REPO_AUTOMATIC_ACTION:$TRAVIS_TAG run test
      - docker push $DOCKER_REPO_AUTOMATIC_ACTION:$TRAVIS_TAG