apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: google-home
spec:
  selector:
    matchLabels:
      app: google-home
  env:
  - name: NODE_ENV
    value: development
  - name: CHOKIDAR_USEPOLLING
    value: 'true'
  volumeMounts:
  - name: u-hub
    mountPath: /usr/src/app
    subPath: google-home
  volumes:
  - name: u-hub
    persistentVolumeClaim:
      claimName: u-hub
