---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: u-hub
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: host.docker.internal
    path: /System/Volumes/Data/Users/dima/Projects/u-hub # CHANGE THIS!!!
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: u-hub
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
