apiVersion: apps/v1
kind: Deployment
metadata:
  name: action
  labels:
    app: action
spec:
  replicas: 1
  selector:
    matchLabels:
      app: action
  template:
    metadata:
      labels:
        app: action
    spec:
      containers:
      - name: action
        image: loginkr/u-hub_action:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: amqp
        - configMapRef:
            name: mongo
        volumeMounts:
        - name: models
          mountPath: /usr/src/app/src/models
      volumes:
        - name: models
          configMap:
            name: models
