apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  51826: "default/apple-homekit:51826"
  1883: "default/mosquitto:1883"
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: udp-services
#   namespace: ingress-nginx
# data:
#   1883: "default/mosquitto:1883"