apiVersion: apps/v1
kind: Deployment
metadata:
  name: homekit-server
  labels:
    app: homekit-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homekit-server
  template:
    metadata:
      labels:
        app: homekit-server
    spec:
      containers:
      - name: homekit-server
        image: loginkr/u-hub_homekit-server:latest
        envFrom:
        - configMapRef:
            name: amqp
        - configMapRef:
            name: mongo
        - configMapRef:
            name: homekit-server
        ports:
        - name: hap
          containerPort: 51826
        # env:
        # - name: PORT
        #   value: 3000
