kind: ConfigMap
apiVersion: v1
metadata:
  name: amqp
data:
  RABBIT_MQ_URI: amqp://rabbit.rabbit
  RABBIT_RECONNECT_INTERVAL: "10000"
  AMQP_APOLLO_QUEUE: apollo
  AMQP_APPLE_HOMEKIT_QUEUE: apple_homekit
  AMQP_GOOGLE_HOME_QUEUE: google_home
  AMQP_SCHEDULED_ACTION_QUEUE: scheduled_action
  AMQP_MQTT_LISTENER_QUEUE: mqtt-listener