apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: loginkr/u-hub_gateway:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        envFrom:
        - configMapRef:
            name: amqp
        - configMapRef:
            name: mongo
        - configMapRef:
            name: gateway
