apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: device
spec:
  selector:
    matchLabels:
      app: device
  env:
  - name: NODE_ENV
    value: development
  - name: CHOKIDAR_USEPOLLING
    value: 'true'
  volumeMounts:
  - name: u-hub
    mountPath: /usr/src/app
    subPath: device
  volumes:
  - name: u-hub
    persistentVolumeClaim:
      claimName: u-hub
