apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple-homekit
  labels:
    app: apple-homekit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apple-homekit
  template:
    metadata:
      labels:
        app: apple-homekit
    spec:
      hostNetwork: true
      containers:
      - name: apple-homekit
        image: loginkr/u-hub_apple-homekit:latest
        envFrom:
        - configMapRef:
            name: amqp
        - configMapRef:
            name: mongo
        - configMapRef:
            name: apple-homekit
        ports:
        - containerPort: 5353
        - containerPort: 51826
        - containerPort: 51827
