apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apple-homekit
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: '0'
spec:
  rules:
  - host: {{DOMAIN}}
    http:
      paths:
      - path: /
        backend:
          serviceName: client
          servicePort: 80
