apiVersion: v1
kind: Service
metadata:
  name: apple-homekit
  labels:
    name: apple-homekit
spec:
  clusterIP: None
  selector:
    app: apple-homekit
  ports:
  - port: 51826
    targetPort: 51826
