apiVersion: v1
kind: Service
metadata:
  name: apple-homekit
  labels:
    name: apple-homekit
spec:
  clusterIP: None
  selector:
    app: apple-homekit
  ports:
  - name: hap1
    port: 5353
    targetPort: 5353
  - name: hap2
    port: 51826
    targetPort: 51826
  - name: hap3
    port: 51827
    targetPort: 51827
